# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

 FactoryGirl.define do
 
  factory :assessment do
    using_materials      'The television was perfect because my students are zombies.'
    involvement          'Class visit to see particular materials'
    staff_experience     5
    staff_availability   4
    space                3
    request_materials    2
    digital_collections  4
    request_course       3
    catalogs             5
    involve_again        'yes'
    better_future        'Provide better food'
    comments             'This is a comment'
    course
    
    trait :negative do
      involve_again        'no'
      better_future        'There will be no future.'
    end
  end
  
  factory :course do
    title 'Test Course Title'
    status 'Scheduled, Claimed'
    contact_email 'course_contact@example.com'
    contact_phone '617-492-TEST'
    contact_first_name 'Jolene'
    contact_last_name 'Patron'
    number_of_students 5
    goal 'Lofty goal'
    duration 2
    repository
    association :primary_contact, factory: :user, admin: true, staff: true
    users { create_list :user, 1, :staff }
    
    trait :homeless do
      status 'Homeless'
      repository nil
      primary_contact nil
      users []
    end

    trait :su do
      status 'Scheduled, Unclaimed'
    end
    
    trait :sc do
      status 'Scheduled, Claimed'
    end
    
    trait :cu do
      status 'Claimed, Unscheduled'
    end
    
    trait :uu do
      status 'Unclaimed, Unscheduled'
    end
    
    trait :cancelled do
      status 'Cancelled'
    end

    trait :closed do
      status 'Closed'
    end
    
    trait :no_users do
      primary_contact nil
      users []
    end
  end
      
  factory :note do
    note_text 'This is some text for the note/'
    staff_comment false
    
    trait :staff_only do
      staff_comment true
    end
    
    trait :by_patron do
      association :user, :factory => [:user, :patron]
    end
    trait :by_admin do
      association :user, :factory => [:user, :admin]
    end
    trait :by_staff do
      association :user, :factory => [:user, :staff]
    end
    
    trait :attached_course do
      course
    end
    
    trait :no_users_course do
      association :course, :factory => [:course, :no_users]
    end
    
    trait :homeless_course do
      association :course, :factory => [:course, :homeless]
    end
  end
  
  factory :repository do
    name 'Test Repository Archive'
    can_edit false
    
    after(:create) do |repository|
      create_list( :user, 3, :staff )
    end
  end
  
  factory :user, :aliases => [:primary_contact] do
    password 'password_cant_be_blank'    
    sequence(:email) { |n| "email_#{n}@example.com" }
    sequence(:username) { |n| "username_#{n}" }
    first_name 'First'
    last_name 'Last'
    admin false
    staff false
    patron false
    superadmin false
    pinuser false
    
    trait :patron do
      patron true
      sequence(:email) { |n| "patron_#{n}@example.com" }
    end

    trait :admin do
      admin true
      sequence(:email) { |n| "admin_#{n}@example.com" }
    end

    trait :superadmin do
      superadmin true
      sequence(:email) { |n| "superadmin_#{n}@example.com" }
    end

    trait :staff do
      staff true
      sequence(:email) { |n| "staff_#{n}@example.com" }
    end    
  end  
 end
