# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do
  
  factory :assessment do
    sequence(:id)
  end
  
  factory :course do
    sequence(:id)
    contact_email 'Test Contact Email'
    contact_phone 'Test Contact Phone'
  end
  
  factory :email do
    sequence(:id)
    message_sent false
  end
  
  factory :item_attribute do
    sequence(:id)
    name 'Test Name'
  end
  
  factory :location do
    sequence(:id)
  end
  
  factory :note do
    sequence(:id)
    note_text 'Test Note Text'
    staff_comment false
  end
  
  factory :repository do
    sequence(:id)
    can_edit false
  end
  
  factory :room do
    sequence(:id)
  end
  
  factory :staff_involvement do
    sequence(:id)
  end
  
  factory :user do
    sequence(:id)
    sequence(:email) do |n|; "person#{n}@example.com"; end
    encrypted_password ''
    admin false
    staff false
    patron true
    sequence(:username) do |n|; "Test Username #{n}"; end
    superadmin false
    pinuser false
  end
  
end
