# Class Request Tool rake tasks
namespace :crt do
  namespace :images do

    desc "Rebuild uploaded image versions"
    task :rebuild => :environment do
          
      # Now rebuild existing images
      AttachedImage.all.each do |image_obj|
        next if /default_image/ =~ image_obj.image.to_s
        if image_obj.image.nil?
          puts "Missing file for image #{image_obj.image_url}"
        else
          puts "Rebuilding #{image_obj.image_url}"
          image_obj.image.recreate_versions!
          image_obj.save!
        end
      end
    end
  end
  
  namespace :cron_task do
    desc "Send email to admins when a class is still homeless after two days."
    task :send_homeless_notices => :environment do
      Notification.homeless_courses_reminder.deliver_later(:queue => 'notifications')
    end

    desc "Set up crontab"
    task :setup_crontab do
      tmp = Tempfile.new('crontab')
      tmp.write `crontab -l`.sub(/^[^\n#]*#CRT_AUTO_CRON_BEGIN.*#CRT_AUTO_CRON_END\n?/m, '')
      tmp.write "#CRT_AUTO_CRON_BEGIN\n"
      tmp.write "# Modified as of #{Time.now}\n"
      tmp.write "# This block is generated by CRT as part of deploy.\n"
      tmp.write "# Please update timestamp if you make manual alterations.\n"

      daily = "1 12 * * *"
      env = "RAILS_ENV=#{ENV['RAILS_ENV']}"
      preamble = "cd #{ENV['RAKE_ROOT'] || Rails.root} && #{env} #{`which rvm`.chomp} default do bundle exec #{`which rake`.chomp} crt:cron_task:"
      redirect = '> /dev/null 2>&1'

      tmp.write "#{daily} #{preamble}#{pm} #{redirect}\n"

      tmp.write "#CRT_AUTO_CRON_END\n"
      tmp.close
      success = system 'crontab', tmp.path
      puts 'Crontab added' if success
    end
  end
end

# Custom seed files (custom_seeds directory)  
namespace :db do
  desc 'A custom seed of the database for QA testing'
  task :custom_seed do
    Dir[File.join(Rails.root, 'db', 'custom_seeds', '*.rb')].each do |filename|
      load(filename) if File.exist?(filename)
    end
  end
end      
