version: '3'
services:
  crt-app:
    container_name: crt-app
    build:
      context: ./
      dockerfile: DockerfileLocal
    env_file: .env
    # Mount directories into the container individually
    # Note: Do not mount the vendor directory into the container as that causes an issue with the bower_components directory
    volumes:
      - ./app:/home/appuser/app
      - ./config:/home/appuser/config
      - ./db:/home/appuser/db
      - ./log:/home/appuser/log
      - ./uploads:/home/appuser/uploads
    ports:
      - "8199:3000"

  postgreshost:
    container_name: postgreshost
    image: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
