version: '3'
services:
  crt-app:
    container_name: crt-app
    build:
      context: ./
      dockerfile: DockerfileLocal
    env_file: .env
    volumes:
      - ./:/usr/src
    ports:
      - "8199:3000"

  postgreshost:
    container_name: postgreshost
    image: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
