development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

qa:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

quality:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
