# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

 FactoryGirl.define do
 
  factory :assessment do
    using_materials      'The television was perfect because my students are zombies.'
    involvement          'Class visit to see particular materials'
    staff_experience     5
    staff_availability   4
    space                3
    request_materials    2
    digital_collections  4
    request_course       3
    catalogs             5
    involve_again        'yes'
    better_future        'Provide better food'
    comments             'This is a comment'
    course
    
    trait :negative do
      involve_again        'no'
      better_future        'There will be no future.'
    end
  end
  
  factory :course do
    title 'Test Course Title'
    status 'Active'
    contact_email 'course_contact@example.com'
    contact_phone '617-492-TEST'
    contact_first_name 'Jolene'
    contact_last_name 'Patron'
    number_of_students 5
    goal 'Lofty goal'
    duration 2
    repository

    trait :with_future_section do
      after(:create) do |course|
        course.sections << build(:section)
      end
    end
    
    trait :with_past_section do
      after(:create) do |course|
        course.sections << build(:section, :past)
      end
    end
    
    trait :scheduled do
      after(:create) do |course|
        course.sections << build(:section)
      end
    end
    
    trait :unscheduled do
      after(:create) do |course|
        course.sections << build(:section, :unscheduled)
      end
    end
              
    trait :homeless do
      repository nil
    end
    
    trait :with_primary_contact do
      primary_contact { create(:user, :staff) }
    end
    
    trait :with_staff do
      users { create_list :user, 1, :staff }
    end
  end
  
  # Site customization
  factory :customization do
    tool_name 'Class Request Tool'
    institution 'Harvard'
    institution_long 'Harvard University'
    default_email_sender 'library_crt@harvard.edu'
    slogan 'We have cool stuff'
    tool_tech_admin_name 'Tech Admin'
    tool_tech_admin_email 'tech@example.com'
    tool_content_admin_name 'Content Admin'
    tool_content_admin_email 'content@example.com'
  end
  
  # Custom text
  factory :custom_text, :class => Admin::CustomText do
    key   'the_key'
    text 'This is custom text'
  end
  
  # Default is scheduled
  factory :section do
    headcount 10
    session_duration 1  # hours
    requested_dates [ Time.now + 3.months ]
    actual_date Time.now + 3.months
    
    trait :unscheduled do
      actual_date nil
    end
    
    trait :past do
      actual_date Time.now - 1.week
    end
  end
      
  factory :note do
    note_text 'This is some text for the note/'
    staff_comment false
    user
    course
    
    trait :staff_only do
      staff_comment true
    end
    
    trait :by_patron do
      association :user, :factory => [:user, :patron]
    end
    trait :by_admin do
      association :user, :factory => [:user, :admin]
    end
    trait :by_staff do
      association :user, :factory => [:user, :staff]
    end
    
    trait :attached_course do
      association :course, :factory => [:course, :with_primary_contact]
    end
    
    trait :no_users_course do
      association :course, :factory => [:course]
    end
    
    trait :homeless_course do
      association :course, :factory => [:course, :homeless]
    end
  end
  
  factory :repository do
    name 'Test Repository Archive'    
  end
    
  factory :user, :aliases => [:primary_contact] do
    password 'password_cant_be_blank'    
    password_confirmation 'password_cant_be_blank'
    sequence(:email) { |n| "email_#{n}@example.com" }
    sequence(:username) { |n| "username_#{n}" }
    first_name 'First'
    last_name 'Last'
    admin false
    staff false
    patron false
    superadmin false
    pinuser false
    
    trait :patron do
      patron true
      sequence(:email) { |n| "patron_#{n}@example.com" }
    end

    trait :admin do
      admin true
      sequence(:email) { |n| "admin_#{n}@example.com" }
    end

    trait :superadmin do
      superadmin true
      sequence(:email) { |n| "superadmin_#{n}@example.com" }
    end

    trait :staff do
      staff true
      sequence(:email) { |n| "staff_#{n}@example.com" }
    end    
  end
  
  factory :additional_patron do
    first_name 'Additional'
    last_name 'Patron'
    email 'additional_patron@example.com'
  end  
 end
